### ISSUE TITLE
How to use this ?

### ISSUE THREAD

**Issue by rata** [thinkingserious/sendgrid-python-dmarc-parser#2]
Hi,

I was looking for an open source tool to parse and display nice result for DMARC reports and found this. But I'm not sure how to run it.

Can you please add some basic instructions ? :)

Thanks a lot,
Rodrigo

**Comment by ecelim** [comment]
> Hi,
> I was looking for an open source tool to parse and display nice result for DMARC reports and found this. But I'm not sure how to run it.
> Can you please add some basic instructions ? :)
> Thanks a lot,
> Rodrigo

Hi rata,

did you find a solution? I have the same demand

**Comment by rata** [comment]
@ecelim To be honest, I don't remember. It was 6 years ago :)

And doesn't seem active since 6 years ago. I'm going to close this issue :)
